/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#0f1419",
        "on-secondary": "#053900",
        "tertiary": "#ffb4ab",
        "primary-container": "#00a3ff",
        "on-tertiary-fixed-variant": "#93000c",
        "on-secondary-container": "#0f6d00",
        "surface-dim": "#0f1419",
        "tertiary-fixed": "#ffdad6",
        "outline": "#88919d",
        "surface-tint": "#98cbff",
        "surface-container-highest": "#30353b",
        "inverse-on-surface": "#2c3137",
        "error-container": "#93000a",
        "secondary-container": "#2ff801",
        "on-surface-variant": "#bec7d4",
        "on-primary-fixed-variant": "#004a77",
        "primary": "#98cbff",
        "surface-container-lowest": "#0a0f14",
        "primary-fixed-dim": "#98cbff",
        "tertiary-fixed-dim": "#ffb4ab",
        "on-secondary-fixed-variant": "#095300",
        "error": "#ffb4ab",
        "secondary": "#d7ffc5",
        "primary-fixed": "#cfe5ff",
        "on-primary-container": "#00375a",
        "surface-container-low": "#171c22",
        "on-tertiary-container": "#6f0007",
        "secondary-fixed": "#79ff5b",
        "inverse-primary": "#00629d",
        "on-surface": "#dfe3ea",
        "tertiary-container": "#ff6e63",
        "on-primary-fixed": "#001d33",
        "surface-bright": "#353a40",
        "on-secondary-fixed": "#022100",
        "surface-container-high": "#262a30",
        "on-tertiary": "#690006",
        "surface-container": "#1b2026",
        "surface-variant": "#30353b",
        "on-background": "#dfe3ea",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#410002",
        "on-error": "#690005",
        "inverse-surface": "#dfe3ea",
        "outline-variant": "#3f4852",
        "secondary-fixed-dim": "#2ae500",
        "on-primary": "#003354",
        "background": "#0f1419"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "40px",
        "gutter": "16px",
        "base": "8px",
        "margin": "20px",
        "xl": "64px"
      },
      fontFamily: {
        "h1": ["Playfair Display", "serif"],
        "h2": ["Playfair Display", "serif"],
        "h3": ["Playfair Display", "serif"],
        "body": ["Outfit", "sans-serif"],
        "body-md": ["Outfit", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"],
        "body-sm": ["Outfit", "sans-serif"],
        "caption": ["Outfit", "sans-serif"],
        "label-caps": ["Playfair Display", "serif"]
      },
      fontSize: {
        "h3": ["24px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "h1": ["40px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "caption": ["12px", {"lineHeight": "1.4", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "h2": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
